### ISSUE TITLE
ALL Maps - route listings

### ISSUE THREAD

**Issue by NichollsC** [CanterburyRegionalCouncil/MetroInfoMaps#16]
Can you  change the route listing order under "by route" to show the following first,

Blue Line
Diamond Harbour Ferry
Orange Line
Orbiter
Purple Line
Yellow Line

Then list the numbered routes

**Comment by SamDrummond** [comment]
This is out of scope as this is the order that they appear in the existing metro site. If this were a change request it would be small (hours not days).

**Comment by NichollsC** [comment]
Hi Sam 

I thought I asked for this in our initial meeting with Iain - yes it was a slight change but I asked for it from the beginning. I was under the impression this was included in the costing

Claire

**Comment by SamDrummond** [comment]
Claire, I don't have any paper trail of this. I will scope it out and if it isn't much effort I will do it.

**Comment by SamDrummond** [comment]
I have completed this. Will be in the next deployment to the test environment.
