### ISSUE TITLE
ALL MAPS - Bus Interchange

### ISSUE THREAD

**Issue by NichollsC** [CanterburyRegionalCouncil/MetroInfoMaps#17]
Can you please place a label over the bus Interchange - the same or similar as current map

e.g. 
![bus interchange](https://cloud.githubusercontent.com/assets/6656769/8273355/fa951368-18bd-11e5-9937-efd1a1e5a168.JPG)

**Comment by SamDrummond** [comment]
Sorry Claire, you might have to zoom the screen shot out a little so I know where you are looking. These issues will either be something that GIS will have to solve, or its possible that this is part of the Google Maps component, which we don't have control over.  If you can give another screenshot zoomed out a little I'll be able to point the issue in the right direction.

**Comment by NichollsC** [comment]
Ignore - this one the image came up later on - may have just been a speed loading issue. But imagery is definitely there now.
