### ISSUE TITLE
PC MAP - Blue Line route

### ISSUE THREAD

**Issue by NichollsC** [CanterburyRegionalCouncil/MetroInfoMaps#18]
Bus stops missing along the following roads,

- Main north Rd between Marshland Rd and Smith St Kaiapoi
- Main north Rd between Harewood Rd and Redwood Library
- All bus stops heading north from the city
- Victoria St
- Salisbury St
- Victoria St
- Kilmore St
- Manchester St
Colombo St - outside South City

**Comment by SamDrummond** [comment]
Closing and resolving to a single issue:
https://github.com/CanterburyRegionalCouncil/MetroInfoMaps/issues/34
