### ISSUE TITLE
PC MAP- Orange Line route

### ISSUE THREAD

**Issue by NichollsC** [CanterburyRegionalCouncil/MetroInfoMaps#19]
Bus stops missing on the following roads;

- Mairehau Rd
- New Brighton Rd
- Manchester St
- St Asaph St,
- Tuam St
- Hagley Ave
- Selwyn St
- Patterson Tce
- Wales St
- Nicholls Rd
- Oakridge St

Bus stops showing on Hills Rd that should not be there

**Comment by SamDrummond** [comment]
Closing and resolving to a single issue:
https://github.com/CanterburyRegionalCouncil/MetroInfoMaps/issues/34
