### ISSUE TITLE
PC MAP - Purple Line

### ISSUE THREAD

**Issue by NichollsC** [CanterburyRegionalCouncil/MetroInfoMaps#21]
Bus stops missing along the following roads

- Ferry Rd between Main Rd and Portman St
- Ferry Rd between Aldwins Rd and Fitzgerald Ave
- St Asaph St
- Tuam St
- Riccarton Ave
- Riccarton Rd
- Ilam Rd
- Maidstone Rd between Ilam Rd and Waimari Rd
- Withells Rd
- Memoral Ave
- Airport
- Roydvale Ave
-Sheffeild Cres

**Comment by SamDrummond** [comment]
Closing and resolving to a single issue:
https://github.com/CanterburyRegionalCouncil/MetroInfoMaps/issues/34
