### ISSUE TITLE
PC MAP - Yellow Line 

### ISSUE THREAD

**Issue by NichollsC** [CanterburyRegionalCouncil/MetroInfoMaps#22]
Route line from Rolleston to Hornby completely missing and all stops on it missing

Stops also missing from the following roads
- Buckleys Rd
- Gloucester St between Stanmore Rd and Manchester St
- Manchester St
- St Asaph St
- Tuam St
- Riccarton Ave
- Riccarton Rd
- Yaldhurst Rd
- Main South Rd between Curletts Rd and Springs Rd
- Hornby Hub
- Kidman St

**Comment by SamDrummond** [comment]
Closing and resolving to a single issue:
https://github.com/CanterburyRegionalCouncil/MetroInfoMaps/issues/34
