### ISSUE TITLE
PC MAP - 17 Bryndwr - Huntsbury

### ISSUE THREAD

**Issue by NichollsC** [CanterburyRegionalCouncil/MetroInfoMaps#23]
Bus stops missing from the following roads
- Sheffield Cres
- Sir William Pickering Dr
- Roydvale Ave
- Moorhouse Ave
- Wilsons Rd

**Comment by SamDrummond** [comment]
Closing and resolving to a single issue:
https://github.com/CanterburyRegionalCouncil/MetroInfoMaps/issues/34
