### ISSUE TITLE
PC MAP- 29 Airport - City

### ISSUE THREAD

**Issue by NichollsC** [CanterburyRegionalCouncil/MetroInfoMaps#25]
Bus stops missing on the following routes;

- Hereford St
- Manchester St
- Kilmore St
- Salisbury St
- Memorial Ave between Roydvale Ave and Airport
- Airport Stop

**Comment by SamDrummond** [comment]
Closing and resolving to a single issue:
https://github.com/CanterburyRegionalCouncil/MetroInfoMaps/issues/34
