### ISSUE TITLE
PC MAP - 44 Shirely & Dallington

### ISSUE THREAD

**Issue by NichollsC** [CanterburyRegionalCouncil/MetroInfoMaps#26]
Bus stops missing from the following roads,

- Manchester St between Oxford Tce and Lichfield St
- Barbadoes St
- Shirley Rd

**Comment by SamDrummond** [comment]
Closing and resolving to a single issue:
https://github.com/CanterburyRegionalCouncil/MetroInfoMaps/issues/34
