### ISSUE TITLE
PC MAP - 60 Hillmorton - Southshore route

### ISSUE THREAD

**Issue by NichollsC** [CanterburyRegionalCouncil/MetroInfoMaps#27]
Bus stops missing from the following roads

- Oram Ave (near corner of Beresford St)
- Marshland Rd between Briggs Rd and Hercules St
- Frankleigh St

**Comment by SamDrummond** [comment]
Closing and resolving to a single issue:
https://github.com/CanterburyRegionalCouncil/MetroInfoMaps/issues/34
