### ISSUE TITLE
TABLET - Android Samsung - mapping issues

### ISSUE THREAD

**Issue by NichollsC** [CanterburyRegionalCouncil/MetroInfoMaps#32]
When I open the link and zoom on the map using fingers on screen the map zooms then jams. I can not scroll across the page. If I hit the minimise button it does nothing. This was using Chrome and IE browsers.
 
When I then pick a route to view it will not change screen to that view, if I choose a location it too will not change.

**Comment by SamDrummond** [comment]
Issue is a bug with pinch zoom on all tablet devices. Have resolved the issue to https://github.com/CanterburyRegionalCouncil/MetroInfoMaps/issues/33
