### ISSUE TITLE
SMART PHONE -Samsung S4 - mapping issues

### ISSUE THREAD

**Issue by NichollsC** [CanterburyRegionalCouncil/MetroInfoMaps#33]
When viewing on my Samsung S4 i have all the same issues as the tablet has - map jams and if I choose another route it does not change, if I choose a location the screen will not change either.

**Comment by SamDrummond** [comment]
I have seen this issue a few times. Can you please confirm what browser you are using on the Samsung S4... is it just the default android browser, as opposed to using chrome?

**Comment by NichollsC** [comment]
Hi Sam

I'm using both Chrome and IE on my Samsung S4 and on my tablet

**Comment by SamDrummond** [comment]
Have resolved as per the bug at the following link - https://github.com/Leaflet/Leaflet/issues/1922. Will deploy for testing.
