### ISSUE TITLE
Bus Stops not displaying properly

### ISSUE THREAD

**Issue by SamDrummond** [CanterburyRegionalCouncil/MetroInfoMaps#34]
The filter query being applied to the bus stop slayer when a route is selected needs tweaking slightly.  At the moment it looks like it is filtering for any stop which has only that route number – some of the stops contain a list of route numbers (these are stops that service more than one route).  In the old viewer we had to build a complex query string that checked for route tags which start with the required route no, end with the required route no, include to route no or equal the route no.

**Comment by NichollsC** [comment]
Have checked bus stops on each route - I am happy they are displaying now
