### ISSUE TITLE
bus stops from previous route still on  map

### ISSUE THREAD

**Issue by NichollsC** [CanterburyRegionalCouncil/MetroInfoMaps#36]
When im in Chrome, I viewed route 28 then switched to route 29 to view bus stops.

The bus stops from route 28 remained on the screen;
![viewing 29 route - additional bus stops on map](https://cloud.githubusercontent.com/assets/6656769/8534976/d3973596-2495-11e5-8771-fe3fce7388db.JPG)

Also happened when viewing route 60 after viewing route 44 - see rougue bus stop on image (ferry rd)
![Uploading 60 after 44.JPG…]()

**Comment by NichollsC** [comment]
This also occurs on IE

**Comment by SamDrummond** [comment]
Claire, similar to issue https://github.com/CanterburyRegionalCouncil/MetroInfoMaps/issues/28, I have seen this issue once or twice but I cannot recreate it either in the development or test environment. Can you please check that you can recreate the issue still?

**Comment by NichollsC** [comment]
I can recreate this issues still , if I look at an individual route and then click on a location then  the map zooms tot that location but only the previous route I was looking at shows on screen instead of all the routes that go past that location. E.g. 
![city centre](https://cloud.githubusercontent.com/assets/6656769/8995924/afdaf558-3768-11e5-8b20-24fc3e771918.JPG)

**Comment by SamDrummond** [comment]
Claire, I think this is how it works in the existing metro info site. In both sites I can do the following workflow:

1. Open the site
2. Click on 'By Route' drop down
3. Select 17 Bryndwr/Huntsbury
4. Click on the 'By Key Location' drop down
5. Select 'Avonhead Shopping Centre'

Result in both maps is that the map zooms to the location but only the previously selected bus route (17 Bryndwr/Huntsbury) is visible on the map.

What would you like to do about this?

**Comment by SamDrummond** [comment]
This is the same as https://github.com/CanterburyRegionalCouncil/MetroInfoMaps/issues/30. So I will close this issue.
