### ISSUE TITLE
bus stops with no ETA within 60min

### ISSUE THREAD

**Issue by NichollsC** [CanterburyRegionalCouncil/MetroInfoMaps#37]
Bus stops with no WTA within 60min do not show information when clicked on - these stops should still show information when clicked on but instead of a time next to "next bus" they should state "no buses within 60min"

![bus stops with no eta](https://cloud.githubusercontent.com/assets/6656769/8535095/b5c915b0-2496-11e5-8be7-8b900a52f3b2.JPG)

**Comment by SamDrummond** [comment]
I can replicate this. In the current application this shows:

Next Bus: N/A

I think that displaying "No busses within 60 minutes" is much nicer. Will implement this for the next test release.

**Comment by SamDrummond** [comment]
This is developed but cannot be adequately tested in the development environment. Will leave open until this can be validated in the test enviroment.

**Comment by SamDrummond** [comment]
For some reason this got reverted in the last release - will be updated for the next version.
